import json
import os
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

def generate_json_report(analysis_result: dict, filename: str) -> dict:
    """Format the raw analysis result into a final structured JSON report."""
    
    # We can add metadata like timestamp, filename, etc.
    report = {
        "metadata": {
            "filename": filename,
            "status": "completed"
        },
        "overall_similarity": analysis_result.get("overall_similarity", 0),
        "ai_summary": analysis_result.get("ai_summary", "Manual review required."),
        "sections": analysis_result.get("sections", {}),
        "flagged_sentences": analysis_result.get("flagged_sentences", []),
        "statistics": {
            "total_sentences": analysis_result.get("total_sentences", 0),
            "plagiarized_count": analysis_result.get("plagiarized_sentences_count", 0)
        }
    }
    
    return report

def generate_docx_report(report_data: dict, size: str = "A4") -> str:
    """Generates a DOCX report with specific page sizing."""
    doc = Document()
    
    # Set Page Size
    section = doc.sections[0]
    sizes = {
        "A4": (8.27, 11.69),
        "A2": (16.54, 23.39),
        "A5": (5.83, 8.27),
        "A6": (4.13, 5.83)
    }
    width, height = sizes.get(size, sizes["A4"])
    section.page_width = Inches(width)
    section.page_height = Inches(height)
    
    # Title
    title = doc.add_heading('Academic Plagiarism Analysis Report', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Summary Table
    doc.add_heading('Summary', level=1)
    doc.add_paragraph(f"Filename: {report_data['metadata']['filename']}")
    doc.add_paragraph(f"Overall Similarity: {report_data['overall_similarity']}%")
    doc.add_paragraph(f"Total Sentences Analyzed: {report_data['statistics']['total_sentences']}")
    doc.add_paragraph(f"Flagged Plagiarism Count: {report_data['statistics']['plagiarized_count']}")
    
    # Section Breakdown
    doc.add_heading('Section Breakdown', level=1)
    for section_name, score in report_data['sections'].items():
        doc.add_paragraph(f"{section_name.capitalize()}: {score}%")
    
    # Flagged Content & Rewrites
    if report_data['flagged_sentences']:
        doc.add_heading('Flagged Content & AI Suggestions', level=1)
        for item in report_data['flagged_sentences']:
            p = doc.add_paragraph()
            run = p.add_run(f"Flagged Sentence ({item['similarity']}% match):")
            run.bold = True
            doc.add_paragraph(item['sentence'], style='Quote')
            
            doc.add_paragraph("Matched Source:", style='Body Text')
            doc.add_paragraph(item['matched_sentence'], style='Quote')
            
            if 'ai_rewrite_suggestion' in item:
                doc.add_paragraph("AI Suggested Rewrite:", style='Body Text')
                rewrite_p = doc.add_paragraph(item['ai_rewrite_suggestion'])
                rewrite_p.paragraph_format.left_indent = Inches(0.5)
            
            doc.add_paragraph("-" * 20)

    # Footer
    doc.add_paragraph("\nGenerated by Srujana AI Plagiarism Scanner.")
    
    # Save
    downloads_dir = os.path.join(os.path.dirname(__file__), '..', 'exports')
    os.makedirs(downloads_dir, exist_ok=True)
    report_filename = f"Report_{size}_{report_data['metadata']['filename']}.docx"
    file_path = os.path.join(downloads_dir, report_filename)
    doc.save(file_path)
    
    return file_path

def save_report_to_db(report: dict, db_connection) -> int:
    """Save the generated report to database (placeholder for actual DB logic)."""
    # Insert assignments, reports, and flagged_sentences based on schema
    pass
